# -*- coding: utf-8 -*-
"""data2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8xaoKcSnils2l_7xRY7nfU-YzLNBcPZ

# La Liga Match Predictor: Unified Data & Modeling Pipeline
This notebook provides a comprehensive workflow that handles:
1. **Data Cleaning & Imputation**: Using Bet365 data to fill holes in Pinnacle/Betbrain records.
2. **Market Consensus**: Aggregating features from multiple bookmakers.
3. **Advanced Feature Engineering**: Implementing Elo ratings (Home/Away), momentum (Form), and fatigue (Rest).
4. **Multi-Model Ensemble**: Training and comparing Logistic Regression, Random Forest, SVM, XGBoost, and a Hybrid Model.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
from datetime import datetime
import requests
import os
import json
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, log_loss, classification_report, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

# Premium Aesthetics
plt.style.use('fivethirtyeight')
sns.set_palette('magma')
plt.rcParams['figure.figsize'] = (14, 10)

"""## 1. Data Loading & Imputation
We fill missing odds from specific bookmakers (like Pinnacle) using Bet365 as a reliable proxy to maintain a consistent longitudinal dataset.
"""

# --- NEW DATA FETCHING LOGIC (from train_pipeline) ---
DATA_URL = "https://www.football-data.co.uk/mmz4281/2526/SP1.csv"
CLEAN_DATA_PATH = "laliga_merged_clean.csv"

def download_data():
    print(f"Downloading latest data from {DATA_URL}...")
    try:
        response = requests.get(DATA_URL, timeout=10)
        if response.status_code == 200:
            os.makedirs("Match Data", exist_ok=True)
            temp_path = os.path.join("Match Data", "SP1_2526.csv")
            with open(temp_path, "wb") as f:
                f.write(response.content)
            return temp_path
        else:
            print(f"[ERROR] Failed to download data: {response.status_code}")
            return None
    except Exception as e:
        print(f"[ERROR] Error downloading data: {str(e)}")
        return None

def merge_and_clean(new_csv_path):
    print("Merging and cleaning data...")
    if not new_csv_path or not os.path.exists(new_csv_path):
        if os.path.exists(CLEAN_DATA_PATH):
            return pd.read_csv(CLEAN_DATA_PATH)
        return None

    new_df = pd.read_csv(new_csv_path)
    if os.path.exists(CLEAN_DATA_PATH):
        old_df = pd.read_csv(CLEAN_DATA_PATH)
        # Standardize date format
        if 'Date' in new_df.columns:
            new_df['Date'] = pd.to_datetime(new_df['Date'], dayfirst=True, errors='coerce')
        if 'Date' in old_df.columns:
            old_df['Date'] = pd.to_datetime(old_df['Date'], errors='coerce')
        
        # Merge logic (simplified)
        merged_df = pd.concat([old_df, new_df], ignore_index=True)
        merged_df.drop_duplicates(subset=['Date', 'HomeTeam', 'AwayTeam'], keep='last', inplace=True)
    else:
        merged_df = new_df

    merged_df.to_csv(CLEAN_DATA_PATH, index=False)
    return merged_df

# Trigger download & merge
new_data_file = download_data()
df = merge_and_clean(new_data_file)

if df is None:
    df = pd.read_csv(CLEAN_DATA_PATH)
# --- END NEW DATA FETCHING LOGIC ---

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df = df.dropna(subset=['Date']).sort_values('Date').reset_index(drop=True)

print(f"[DATA] Dataset contains {len(df)} matches from {df['Date'].min().year} to {df['Date'].max().year}.")

print("[INFO] Imputing missing odds...")
odds_targets = {'PS': 'B365', 'BbAv': 'B365'}
for target, source in odds_targets.items():
    for suffix in ['H', 'D', 'A']:
        col = target + suffix
        ref = source + suffix
        df[col] = df[col].fillna(df[ref])

df['Market_H'] = df[['B365H', 'BbAvH', 'PSH']].mean(axis=1)
df['Market_D'] = df[['B365D', 'BbAvD', 'PSD']].mean(axis=1)
df['Market_A'] = df[['B365A', 'BbAvA', 'PSA']].mean(axis=1)

print("[SUCCESS] Data cleaned and imputation complete.")

"""## 2. Advanced Feature Engineering
We calculate dynamic Elo ratings for both teams (showing Home/Away strength), tracking their momentum via 5-match rolling points, and calculating rest periods.
"""

def expected_result(elo_a, elo_b):
    return 1 / (1 + 10 ** ((elo_b - elo_a) / 400))

def update_elo(elo_home, elo_away, result, k=25, home_adv=75):
    exp_home = expected_result(elo_home + home_adv, elo_away)
    exp_away = 1 - exp_home
    if result == 1: score_home, score_away = 1, 0
    elif result == 0: score_home, score_away = 0.5, 0.5
    else: score_home, score_away = 0, 1
    new_home = elo_home + k * (score_home - exp_home)
    new_away = elo_away + k * (score_away - exp_away)
    return new_home, new_away

teams = sorted(list(set(df['HomeTeam']).union(df['AwayTeam'])))
elo = {team: 1500 for team in teams}
team_history = {team: {'dates': [], 'results': [], 'goals_for': [], 'goals_against': []} for team in teams}
feature_rows = []

print("[INFO] Synthesizing advanced features...")
for idx, row in df.iterrows():
    home, away, date = row['HomeTeam'], row['AwayTeam'], row['Date']
    hg, ag, res_label = row['FTHG'], row['FTAG'], row['FTR']
    res = 1 if res_label == 'H' else (0 if res_label == 'D' else -1)

    elo_h_before, elo_a_before = elo[home], elo[away]
    elo_diff = (elo_h_before + 75) - elo_a_before

    def get_pts(res_list):
        return sum(res_list[-5:]) if res_list else 0

    h_form = get_pts(team_history[home]['results'])
    a_form = get_pts(team_history[away]['results'])
    h_gd = sum(team_history[home]['goals_for'][-5:]) - sum(team_history[home]['goals_against'][-5:])
    a_gd = sum(team_history[away]['goals_for'][-5:]) - sum(team_history[away]['goals_against'][-5:])
    h_rest = (date - team_history[home]['dates'][-1]).days if team_history[home]['dates'] else 14
    a_rest = (date - team_history[away]['dates'][-1]).days if team_history[away]['dates'] else 14

    feature_rows.append({
        'Date': date, 'HomeTeam': home, 'AwayTeam': away,
        'EloH': elo_h_before, 'EloA': elo_a_before, 'EloDiff': elo_diff,
        'H_Form': h_form, 'A_Form': a_form, 'H_GD': h_gd, 'A_GD': a_gd,
        'H_Rest': min(h_rest, 20), 'A_Rest': min(a_rest, 20),
        'Market_H': row['Market_H'], 'Market_D': row['Market_D'], 'Market_A': row['Market_A'],
        'Target': 0 if res == 1 else (1 if res == 0 else 2)
    })

    team_history[home]['dates'].append(date)
    # Home Points: 3 for win, 1 for draw, 0 for loss
    team_history[home]['results'].append(3 if res == 1 else (1 if res == 0 else 0))
    team_history[home]['goals_for'].append(hg); team_history[home]['goals_against'].append(ag)
    
    team_history[away]['dates'].append(date)
    # Away Points: 3 for win, 1 for draw, 0 for loss
    team_history[away]['results'].append(3 if res == -1 else (1 if res == 0 else 0))
    team_history[away]['goals_for'].append(ag); team_history[away]['goals_against'].append(hg)

    elo[home], elo[away] = update_elo(elo_h_before, elo_a_before, res)

feats_df = pd.DataFrame(feature_rows)
print("[SUCCESS] Feature synthesis complete.")
feats_df.sample(5)

"""## 3. Global Correlation Analysis
Visualizing how the engineered features like Elo ratings and Market odds correlate with match outcomes.
"""

corr = feats_df.drop(['Date', 'HomeTeam', 'AwayTeam'], axis=1).corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdYlGn', center=0)
#plt.title('Global Correlation Analysis (Including Elo Home/Away Strength)', fontsize=16)
#plt.show()

"""## 4. Multi-Model Training & Evaluation
We use an optimized feature set for training, removing redundant or low-signal features while keeping them available for the Hybrid logic.
"""

from sklearn.metrics import log_loss

feature_cols = ['EloDiff', 'H_GD', 'A_GD', 'Market_H', 'Market_D', 'Market_A']

# 1. Chronological Split (80/20)
split_idx = int(len(feats_df) * 0.8)
train_df = feats_df.iloc[:split_idx]
test_df = feats_df.iloc[split_idx:]

X_train, y_train = train_df[feature_cols], train_df['Target']
X_test, y_test = test_df[feature_cols], test_df['Target']
test_meta = test_df[['EloH', 'EloA']]

print(f"[INFO] Training on {len(X_train)} matches, testing on {len(X_test)} matches")

# 2. Initialize Models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Random Forest': RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42),
    'SVM': SVC(probability=True, kernel='rbf', C=1.0),
    'XGBoost': XGBClassifier(n_estimators=100, max_depth=4, learning_rate=0.05, objective='multi:softprob', num_class=3)
}

results = []

# 3. Train & Evaluate
for name, model in models.items():
    print(f"[INFO] Training {name}...")
    model.fit(X_train, y_train)
    probs = model.predict_proba(X_test)
    preds = model.predict(X_test)

    acc = accuracy_score(y_test, preds)
    loss = log_loss(y_test, probs)
    results.append({'Model': name, 'Accuracy': acc, 'Log Loss': loss, 'Probs': probs})

# 4. Hybrid Model Logic
def get_elo_win_probs(elo_h, elo_a, home_adv=75, draw_prob=0.25):
    # Standard Elo Win Probability
    win_h = 1 / (1 + 10 ** ((elo_a - (elo_h + home_adv)) / 400))
    win_a = 1 / (1 + 10 ** (((elo_h + home_adv) - elo_a) / 400))

    # Scaling for 3 outcomes (Home, Draw, Away)
    rem_prob = 1.0 - draw_prob
    p_h = win_h * rem_prob
    p_a = win_a * rem_prob
    return np.array([p_h, draw_prob, p_a])

print("[INFO] Calculating Hybrid Predictions...")
elo_probs = np.array([get_elo_win_probs(row['EloH'], row['EloA']) for _, row in test_meta.iterrows()])

# Get probabilities for individual ML models by name
ml_model_probs_dict = {res['Model']: res['Probs'] for res in results}

# Initialize dictionary to store hybrid model weights
hybrid_weights = {}

# --- Hybrid (XGBoost-Elo) --- START ---
if 'XGBoost' in ml_model_probs_dict:
    xgb_probs = ml_model_probs_dict['XGBoost']

    best_accuracy_xgb_elo = 0
    best_xgb_weight = 0
    best_elo_weight_for_xgb = 0

    print("\n[INFO] Optimizing weights for Hybrid (XGBoost-Elo)...")
    for current_xgb_weight in np.arange(0.00, 1.01, 0.01):
        current_elo_weight = 1 - current_xgb_weight

        current_xgb_weight = round(current_xgb_weight, 2)
        current_elo_weight = round(current_elo_weight, 2)

        current_hybrid_probs = (current_xgb_weight * xgb_probs) + (current_elo_weight * elo_probs)
        current_hybrid_preds = np.argmax(current_hybrid_probs, axis=1)
        current_hybrid_acc = accuracy_score(y_test, current_hybrid_preds)

        if current_hybrid_acc > best_accuracy_xgb_elo:
            best_accuracy_xgb_elo = current_hybrid_acc
            best_xgb_weight = current_xgb_weight
            best_elo_weight_for_xgb = current_elo_weight

    print(f"Optimal XGBoost Weight (for Elo-XGB Hybrid): {best_xgb_weight:.2f}")
    print(f"Optimal Elo Weight (for Elo-XGB Hybrid): {best_elo_weight_for_xgb:.2f}")
    print(f"Highest Accuracy Achieved (Elo-XGB Hybrid): {best_accuracy_xgb_elo:.4f}")

    hybrid_xgb_elo_probs = (best_xgb_weight * xgb_probs) + (best_elo_weight_for_xgb * elo_probs)
    hybrid_xgb_elo_preds = np.argmax(hybrid_xgb_elo_probs, axis=1)
    hybrid_xgb_elo_acc = accuracy_score(y_test, hybrid_xgb_elo_preds)
    hybrid_xgb_elo_loss = log_loss(y_test, hybrid_xgb_elo_probs)
    results.append({'Model': 'Hybrid (XGBoost-Elo)', 'Accuracy': hybrid_xgb_elo_acc, 'Log Loss': hybrid_xgb_elo_loss, 'Probs': hybrid_xgb_elo_probs})
    hybrid_weights['Hybrid (XGBoost-Elo)'] = {'model_w': best_xgb_weight, 'elo_w': best_elo_weight_for_xgb}
else:
    print("XGBoost probabilities not found. Skipping Hybrid (XGBoost-Elo) model.")
# --- Hybrid (XGBoost-Elo) --- END ---

# --- Hybrid (Random Forest-Elo) --- START ---
if 'Random Forest' in ml_model_probs_dict:
    rf_probs = ml_model_probs_dict['Random Forest']

    best_accuracy_rf_elo = 0
    best_rf_weight = 0
    best_elo_weight_for_rf = 0

    print("\n[INFO] Optimizing weights for Hybrid (Random Forest-Elo)...")
    for current_rf_weight in np.arange(0.00, 1.01, 0.01):
        current_elo_weight = 1 - current_rf_weight

        current_rf_weight = round(current_rf_weight, 2)
        current_elo_weight = round(current_elo_weight, 2)

        current_hybrid_probs = (current_rf_weight * rf_probs) + (current_elo_weight * elo_probs)
        current_hybrid_preds = np.argmax(current_hybrid_probs, axis=1)
        current_hybrid_acc = accuracy_score(y_test, current_hybrid_preds)

        if current_hybrid_acc > best_accuracy_rf_elo:
            best_accuracy_rf_elo = current_hybrid_acc
            best_rf_weight = current_rf_weight
            best_elo_weight_for_rf = current_elo_weight

    print(f"Optimal Random Forest Weight (for RF-Elo Hybrid): {best_rf_weight:.2f}")
    print(f"Optimal Elo Weight (for RF-Elo Hybrid): {best_elo_weight_for_rf:.2f}")
    print(f"Highest Accuracy Achieved (RF-Elo Hybrid): {best_accuracy_rf_elo:.4f}")

    hybrid_rf_elo_probs = (best_rf_weight * rf_probs) + (best_elo_weight_for_rf * elo_probs)
    hybrid_rf_elo_preds = np.argmax(hybrid_rf_elo_probs, axis=1)
    hybrid_rf_elo_acc = accuracy_score(y_test, hybrid_rf_elo_preds)
    hybrid_rf_elo_loss = log_loss(y_test, hybrid_rf_elo_probs)
    results.append({'Model': 'Hybrid (Random Forest-Elo)', 'Accuracy': hybrid_rf_elo_acc, 'Log Loss': hybrid_rf_elo_loss, 'Probs': hybrid_rf_elo_probs})
    hybrid_weights['Hybrid (Random Forest-Elo)'] = {'model_w': best_rf_weight, 'elo_w': best_elo_weight_for_rf}
else:
    print("Random Forest probabilities not found. Skipping Hybrid (Random Forest-Elo) model.")
# --- Hybrid (Random Forest-Elo) --- END ---
# --- Hybrid (SVM-Elo) --- START ---
if 'SVM' in ml_model_probs_dict:
    svm_probs = ml_model_probs_dict['SVM']

    best_accuracy_svm_elo = 0
    best_svm_weight = 0
    best_elo_weight_for_svm = 0

    print("\n[INFO] Optimizing weights for Hybrid (SVM-Elo)...")
    for current_svm_weight in np.arange(0.00, 1.01, 0.01):
        current_elo_weight = round(1 - current_svm_weight, 2)
        current_svm_weight = round(current_svm_weight, 2)

        current_hybrid_probs = (current_svm_weight * svm_probs) + (current_elo_weight * elo_probs)
        current_hybrid_preds = np.argmax(current_hybrid_probs, axis=1)
        current_hybrid_acc = accuracy_score(y_test, current_hybrid_preds)

        if current_hybrid_acc > best_accuracy_svm_elo:
            best_accuracy_svm_elo = current_hybrid_acc
            best_svm_weight = current_svm_weight
            best_elo_weight_for_svm = current_elo_weight

    print(f"Optimal SVM Weight: {best_svm_weight:.2f} | Elo Weight: {best_elo_weight_for_svm:.2f}")

    hybrid_svm_elo_probs = (best_svm_weight * svm_probs) + (best_elo_weight_for_svm * elo_probs)
    hybrid_svm_elo_acc = accuracy_score(y_test, np.argmax(hybrid_svm_elo_probs, axis=1))
    hybrid_svm_elo_loss = log_loss(y_test, hybrid_svm_elo_probs)
    results.append({'Model': 'Hybrid (SVM-Elo)', 'Accuracy': hybrid_svm_elo_acc, 'Log Loss': hybrid_svm_elo_loss, 'Probs': hybrid_svm_elo_probs})
    hybrid_weights['Hybrid (SVM-Elo)'] = {'model_w': best_svm_weight, 'elo_w': best_elo_weight_for_svm}
# --- Hybrid (SVM-Elo) --- END ---

# --- Hybrid (Logistic Regression-Elo) --- START ---
if 'Logistic Regression' in ml_model_probs_dict:
    lr_probs = ml_model_probs_dict['Logistic Regression']

    best_accuracy_lr_elo = 0
    best_lr_weight = 0
    best_elo_weight_for_lr = 0

    print("\n[INFO] Optimizing weights for Hybrid (LR-Elo)...")
    for current_lr_weight in np.arange(0.00, 1.01, 0.01):
        current_elo_weight = round(1 - current_lr_weight, 2)
        current_lr_weight = round(current_lr_weight, 2)

        current_hybrid_probs = (current_lr_weight * lr_probs) + (current_elo_weight * elo_probs)
        current_hybrid_preds = np.argmax(current_hybrid_probs, axis=1)
        current_hybrid_acc = accuracy_score(y_test, current_hybrid_preds)

        if current_hybrid_acc > best_accuracy_lr_elo:
            best_accuracy_lr_elo = current_hybrid_acc
            best_lr_weight = current_lr_weight
            best_elo_weight_for_lr = current_elo_weight

    print(f"Optimal LR Weight: {best_lr_weight:.2f} | Elo Weight: {best_elo_weight_for_lr:.2f}")

    hybrid_lr_elo_probs = (best_lr_weight * lr_probs) + (best_elo_weight_for_lr * elo_probs)
    hybrid_lr_elo_acc = accuracy_score(y_test, np.argmax(hybrid_lr_elo_probs, axis=1))
    hybrid_lr_elo_loss = log_loss(y_test, hybrid_lr_elo_probs)
    results.append({'Model': 'Hybrid (LR-Elo)', 'Accuracy': hybrid_lr_elo_acc, 'Log Loss': hybrid_lr_elo_loss, 'Probs': hybrid_lr_elo_probs})
    hybrid_weights['Hybrid (LR-Elo)'] = {'model_w': best_lr_weight, 'elo_w': best_elo_weight_for_lr}
# --- Hybrid (Logistic Regression-Elo) --- END ---
# 5. Display Comparison Table
comparison_df = pd.DataFrame(results)[['Model', 'Accuracy', 'Log Loss']].sort_values(by='Accuracy', ascending=False)
print("\n Model Performance Comparison:")
#display(comparison_df)

# 6. Final Classification Report (Hybrid)
# Determine which hybrid model had the best performance overall to display its detailed report
final_best_hybrid_model_name = comparison_df.iloc[0]['Model']
final_hybrid_preds = None
for res in results:
    if res['Model'] == final_best_hybrid_model_name:
        final_hybrid_preds = np.argmax(res['Probs'], axis=1)
        break

if final_hybrid_preds is not None:
    print(f"\n[REPORT] Detailed Report for {final_best_hybrid_model_name}:")
    print(classification_report(y_test, final_hybrid_preds, target_names=['Home', 'Draw', 'Away']))
else:
    print("\n Could not generate a detailed report for the best hybrid model.")

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, log_loss

# 1. Update/Initialize the models dictionary
models.update({
    'LightGBM': LGBMClassifier(n_estimators=100, learning_rate=0.05, num_leaves=31, random_state=42, verbose=-1),
    'CatBoost': CatBoostClassifier(iterations=100, learning_rate=0.05, depth=6, verbose=False, random_state=42)
})

# 2. Train & Evaluate the Base ML Models
for name in ['LightGBM', 'CatBoost']:
    print(f"[INFO] Training {name}...")
    model = models[name]
    model.fit(X_train, y_train)
    probs = model.predict_proba(X_test)
    preds = model.predict(X_test)

    acc = accuracy_score(y_test, preds)
    loss = log_loss(y_test, probs)

    # --- DE-DUPLICATION LOGIC ---
    # Removes any existing row for this model before adding the new one
    results = [r for r in results if r['Model'] != name]

    results.append({'Model': name, 'Accuracy': acc, 'Log Loss': loss, 'Probs': probs})
    ml_model_probs_dict[name] = probs

# 3. Optimized Hybrid Logic for LightGBM
if 'LightGBM' in ml_model_probs_dict:
    lgb_probs = ml_model_probs_dict['LightGBM']
    best_acc_lgb, best_w_lgb, best_elo_w_lgb = 0, 0, 0

    print("\n[INFO] Optimizing weights for Hybrid (LightGBM-Elo)...")
    for w in np.arange(0.00, 1.01, 0.01):
        w = round(w, 2)
        elo_w = round(1 - w, 2)

        curr_hybrid_probs = (w * lgb_probs) + (elo_w * elo_probs)
        curr_hybrid_preds = np.argmax(curr_hybrid_probs, axis=1)
        curr_acc = accuracy_score(y_test, curr_hybrid_preds)

        if curr_acc > best_acc_lgb:
            best_acc_lgb, best_w_lgb, best_elo_w_lgb = curr_acc, w, elo_w

    print(f"[BEST] Optimal LightGBM Weight: {best_w_lgb:.2f} | Elo Weight: {best_elo_w_lgb:.2f}")

    final_hybrid_lgb_probs = (best_w_lgb * lgb_probs) + (best_elo_w_lgb * elo_probs)

    # De-duplicate Hybrid entry
    results = [r for r in results if r['Model'] != 'Hybrid (LightGBM-Elo)']
    results.append({
        'Model': 'Hybrid (LightGBM-Elo)',
        'Accuracy': best_acc_lgb,
        'Log Loss': log_loss(y_test, final_hybrid_lgb_probs),
        'Probs': final_hybrid_lgb_probs
    })
    hybrid_weights['Hybrid (LightGBM-Elo)'] = {'model_w': best_w_lgb, 'elo_w': best_elo_w_lgb}

# 4. Optimized Hybrid Logic for CatBoost
if 'CatBoost' in ml_model_probs_dict:
    cat_probs = ml_model_probs_dict['CatBoost']
    best_acc_cat, best_w_cat, best_elo_w_cat = 0, 0, 0

    print("[INFO] Optimizing weights for Hybrid (CatBoost-Elo)...")
    for w in np.arange(0.00, 1.01, 0.01):
        w = round(w, 2)
        elo_w = round(1 - w, 2)

        curr_hybrid_probs = (w * cat_probs) + (elo_w * elo_probs)
        curr_hybrid_preds = np.argmax(curr_hybrid_probs, axis=1)
        curr_acc = accuracy_score(y_test, curr_hybrid_preds)

        if curr_acc > best_acc_cat:
            best_acc_cat, best_w_cat, best_elo_w_cat = curr_acc, w, elo_w

    print(f"[BEST] Optimal CatBoost Weight: {best_w_cat:.2f} | Elo Weight: {best_elo_w_cat:.2f}")

    final_hybrid_cat_probs = (best_w_cat * cat_probs) + (best_elo_w_cat * elo_probs)

    # De-duplicate Hybrid entry
    results = [r for r in results if r['Model'] != 'Hybrid (CatBoost-Elo)']
    results.append({
        'Model': 'Hybrid (CatBoost-Elo)',
        'Accuracy': best_acc_cat,
        'Log Loss': log_loss(y_test, final_hybrid_cat_probs),
        'Probs': final_hybrid_cat_probs
    })
    hybrid_weights['Hybrid (CatBoost-Elo)'] = {'model_w': best_w_cat, 'elo_w': best_elo_w_cat}

# 5. Display Clean Leaderboard
comparison_df = pd.DataFrame(results)[['Model', 'Accuracy', 'Log Loss']].sort_values(by='Accuracy', ascending=False)
print("\n Final Model Performance Comparison (Clean):")
print(comparison_df)

"""### Confusion Matrices for Top 3 Models

Below are the confusion matrices for the top 3 performing models, providing a detailed breakdown of correct and incorrect predictions for each outcome (Home, Draw, Away).
"""



import pickle
import json
import os

# 1. Identify the top 3 models
top_3_names = comparison_df.head(3)['Model'].tolist()
save_dir = "saved_models_pkl"

# Create a directory for models if it doesn't exist
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

# 2. Hybrid weight mapping (Already populated during training)
print(f"[INFO] Saving top 3 models as .pkl to: '{save_dir}'\n")

for name in top_3_names:
    # Clean filename
    clean_name = name.lower().replace(' ', '_').replace('(', '').replace(')', '').replace('-', '_')
    model_path = os.path.join(save_dir, f"{clean_name}.pkl")

    # CASE A: Save Base Models
    if name in models:
        with open(model_path, 'wb') as f:
            pickle.dump(models[name], f)
        print(f"[SUCCESS] Saved Base Model: {model_path}")

    # CASE B: Save Hybrids
    elif 'Hybrid' in name:
        # Extract the base model part (e.g., "XGBoost" from "Hybrid (XGBoost-Elo)")
        base_key = next((k for k in models.keys() if k in name), None)

        if base_key:
            # Save the ML component
            with open(model_path, 'wb') as f:
                pickle.dump(models[base_key], f)

            # Save the weight component
            weights_path = os.path.join(save_dir, f"{clean_name}_weights.json")
            with open(weights_path, 'w') as f:
                json.dump(hybrid_weights.get(name, {}), f)

            print(f"[SUCCESS] Saved Hybrid: {model_path} (+ weights JSON)")

print("\n[DONE] All set! Your .pkl files are ready in the local folder.")

# 3. Export current_team_stats.csv for Dashboard
STATS_PATH = "current_team_stats.csv"
print(f"[INFO] Exporting {STATS_PATH}...")

# Compute actual league-average odds from the dataset as fallback values
avg_market_h = df['Market_H'].mean() if 'Market_H' in df.columns and df['Market_H'].notna().any() else 2.10
avg_market_d = df['Market_D'].mean() if 'Market_D' in df.columns and df['Market_D'].notna().any() else 3.30
avg_market_a = df['Market_A'].mean() if 'Market_A' in df.columns and df['Market_A'].notna().any() else 3.50

latest_stats = []
for team in teams:
    # Get latest Elo, Form, GD from team_history
    form = sum(team_history[team]['results'][-5:]) if team_history[team]['results'] else 0
    gd = sum(team_history[team]['goals_for'][-5:]) - sum(team_history[team]['goals_against'][-5:]) if team_history[team]['goals_for'] else 0
    
    latest_stats.append({
        'Team': team,
        'Elo': elo[team],
        'Form': form,
        'GD': gd,
        'Market_H': round(avg_market_h, 2),
        'Market_D': round(avg_market_d, 2),
        'Market_A': round(avg_market_a, 2)
    })
pd.DataFrame(latest_stats).to_csv(STATS_PATH, index=False)

# 4. Export model_metrics.json for Dashboard
METRICS_PATH = os.path.join(save_dir, "model_metrics.json")
print(f"[INFO] Exporting {METRICS_PATH}...")

# Collect metrics for ALL models trained in 'results'
all_metrics = {}
for res in results:
    name = res['Model']
    probs = res['Probs']
    preds = np.argmax(probs, axis=1)
    
    # Calculate confusion matrix for each model
    cm = confusion_matrix(y_test, preds)
    
    # Get weights if hybrid
    weights = hybrid_weights.get(name, {"model_w": 1.0, "elo_w": 0.0})
    
    # Extract ML weight from hybrid_weights
    ml_w = weights.get('model_w', 1.0)
    
    all_metrics[name] = {
        "accuracy": float(res['Accuracy']),
        "log_loss": float(res['Log Loss']),
        "ml_weight": float(ml_w),
        "elo_weight": float(weights.get('elo_w', 1.0 - ml_w)),
        "confusion_matrix": cm.tolist()
    }

with open(METRICS_PATH, 'w') as f:
    json.dump(all_metrics, f, indent=4)

# --- LIVE ODDS AUTOMATION (The Odds API) ---
def fetch_live_odds():
    print("\n[INFO] Fetching Live Odds from The Odds API...")
    config_path = "config.json"
    if not os.path.exists(config_path):
        print("[ERROR] config.json missing. Skipping Live Odds fetch.")
        return

    import requests
    with open(config_path, 'r') as f:
        conf = json.load(f)

    api_key = conf.get("THE_ODDS_API_KEY")
    sport = conf.get("SPORT", "soccer_spain_la_liga")
    url = f"https://api.the-odds-api.com/v4/sports/{sport}/odds/"
    
    params = {
        'apiKey': api_key,
        'regions': conf.get("REGIONS", "eu,us,au,uk"),
        'markets': conf.get("MARKETS", "h2h"),
        'oddsFormat': conf.get("ODDS_FORMAT", "decimal")
    }

    try:
        response = requests.get(url, params=params, timeout=10)
        if response.status_code != 200:
            print(f"[ERROR] API failed: {response.status_code}")
            return
        
        data = response.json()
        upcoming_matches = []

        for match in data:
            home_team = match['home_team']
            away_team = match['away_team']
            start_time = match['commence_time']
            
            # Extract H2H odds
            h_odds, d_odds, a_odds = [], [], []
            for bookie in match['bookmakers']:
                market = next((m for m in bookie['markets'] if m['key'] == 'h2h'), None)
                if market:
                    for outcome in market['outcomes']:
                        if outcome['name'] == home_team: h_odds.append(outcome['price'])
                        elif outcome['name'] == away_team: a_odds.append(outcome['price'])
                        else: d_odds.append(outcome['price'])

            if h_odds:
                upcoming_matches.append({
                    'Home': home_team,
                    'Away': away_team,
                    'Time': start_time,
                    'Mean_H': round(sum(h_odds) / len(h_odds), 2),
                    'Mean_D': round(sum(d_odds) / len(d_odds), 2),
                    'Mean_A': round(sum(a_odds) / len(a_odds), 2),
                    'Sources': len(h_odds)
                })

        with open("upcoming_odds.json", 'w') as f:
            json.dump(upcoming_matches, f, indent=4)
        print(f"[SUCCESS] Automated Odds update: {len(upcoming_matches)} fixtures synced.")

    except Exception as e:
        print(f"[ERROR] Live Odds update failed: {str(e)}")

# Execute fetch
fetch_live_odds()

print("[SUCCESS] Dashboard assets and live odds updated successfully.")